// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.CncModels
{
    /// <summary>
    /// &#27231;&#21488;&#31278;&#39006;
    /// </summary>
    [Table("cnc_models")]
    public partial class CncModel
    {
        public CncModel()
        {
            MachineInformations = new HashSet<MachineInformation>();
        }

        /// <summary>
        /// 唯一碼
        /// </summary>
        [Key]
        [Column("id", TypeName = "int(5)")]
        public int Id { get; set; }
        /// <summary>
        /// &#27231;&#21488;&#31278;&#39006;&#21517;&#31281;
        /// </summary>
        [Required]
        [Column("name", TypeName = "varchar(255)")]
        public string Name { get; set; }
        /// <summary>
        /// &#26032;&#22686;&#26178;&#38291;
        /// </summary>
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }

        [InverseProperty(nameof(MachineInformation.Model))]
        public virtual ICollection<MachineInformation> MachineInformations { get; set; }
    }
}