// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.CncModels
{
    /// <summary>
    /// &#27231;&#21488;&#30446;&#21069;&#29376;&#27841;
    /// </summary>
    [Table("machine_current_status")]
    public partial class MachineCurrentStatus
    {
        /// <summary>
        /// 唯一碼
        /// </summary>
        [Column("id", TypeName = "int(5)")]
        public int Id { get; set; }
        /// <summary>
        /// &#27231;&#21488;&#29376;&#24907;
        /// </summary>
        [Column("status", TypeName = "int(1)")]
        public int? Status { get; set; }
        /// <summary>
        /// &#27284;&#26696;&#21517;&#31281;
        /// </summary>
        [Column("nc_name", TypeName = "varchar(100)")]
        public string NcName { get; set; }
        /// <summary>
        /// &#31243;&#24335;&#35387;&#35299;
        /// </summary>
        [Column("nc_comment", TypeName = "varchar(100)")]
        public string NcComment { get; set; }
        /// <summary>
        /// &#20027;&#36600;&#20992;&#34399;
        /// </summary>
        [Column("spindle_tool_number", TypeName = "varchar(50)")]
        public string SpindleToolNumber { get; set; }
        /// <summary>
        /// &#23526;&#38555;&#36681;&#36895;
        /// </summary>
        [Column("actully_spindle_speed", TypeName = "varchar(100)")]
        public string ActullySpindleSpeed { get; set; }
        /// <summary>
        /// &#23526;&#38555;&#36914;&#32102;&#29575;
        /// </summary>
        [Column("actully_spindle_feedrate", TypeName = "varchar(100)")]
        public string ActullySpindleFeedrate { get; set; }
        /// <summary>
        /// &#24490;&#29872;&#26178;&#38291;
        /// </summary>
        [Column("cycle_time", TypeName = "varchar(100)")]
        public string CycleTime { get; set; }
        /// <summary>
        /// &#32317;&#36939;&#36681;&#26178;&#38291;
        /// </summary>
        [Column("run_time", TypeName = "varchar(100)")]
        public string RunTime { get; set; }
        /// <summary>
        /// &#21152;&#24037;&#37096;&#21697;&#25976;
        /// </summary>
        [Column("parts_count", TypeName = "int(5)")]
        public int? PartsCount { get; set; }
        /// <summary>
        /// &#27231;&#26800;&#24231;&#27161;JSON
        /// </summary>
        [Column("machine_axis", TypeName = "varchar(255)")]
        public string MachineAxis { get; set; }
        /// <summary>
        /// &#26356;&#26032;&#26178;&#38291;
        /// </summary>
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
    }
}