// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.CncModels
{
    /// <summary>
    /// &#27231;&#21488;&#29376;&#24907;&#32000;&#37636;
    /// </summary>
    [Table("machine_logs")]
    public partial class MachineLog
    {
        /// <summary>
        /// 唯一碼
        /// </summary>
        [Key]
        [Column("id", TypeName = "int(20)")]
        public int Id { get; set; }
        /// <summary>
        /// &#27231;&#21488;ID
        /// </summary>
        [Column("machine_id", TypeName = "int(5)")]
        public int MachineId { get; set; }
        /// <summary>
        /// &#27231;&#21488;&#29376;&#24907;
        /// </summary>
        [Column("status", TypeName = "int(1)")]
        public int Status { get; set; }
        /// <summary>
        /// &#27284;&#26696;ID
        /// </summary>
        [Column("file_id", TypeName = "int(5)")]
        public int? FileId { get; set; }
        /// <summary>
        /// &#21152;&#24037;&#37096;&#21697;&#25976;
        /// </summary>
        [Column("completed_number", TypeName = "int(5)")]
        public int? CompletedNumber { get; set; }
        /// <summary>
        /// &#38283;&#22987;&#26178;&#38291;
        /// </summary>
        [Column("start_time", TypeName = "timestamp")]
        public DateTime StartTime { get; set; }
        /// <summary>
        /// &#32080;&#26463;&#26178;&#38291;
        /// </summary>
        [Column("end_time", TypeName = "timestamp")]
        public DateTime? EndTime { get; set; }
        /// <summary>
        /// &#25345;&#32396;&#26178;&#38291;
        /// </summary>
        [Column("duration_time")]
        public double? DurationTime { get; set; }
        /// <summary>
        /// &#21152;&#24037;&#26178;&#38291;
        /// </summary>
        [Column("action_time")]
        public double? ActionTime { get; set; }
        /// <summary>
        /// &#31227;&#21205;&#26178;&#38291;
        /// </summary>
        [Column("move_time")]
        public double? MoveTime { get; set; }
        /// <summary>
        /// &#35686;&#22577;&#34399;&#30908;
        /// </summary>
        [Column("alarm_number", TypeName = "varchar(255)")]
        public string AlarmNumber { get; set; }
        /// <summary>
        /// &#35686;&#22577;&#35338;&#24687;
        /// </summary>
        [Column("alarm_message", TypeName = "varchar(255)")]
        public string AlarmMessage { get; set; }

        [ForeignKey(nameof(MachineId))]
        [InverseProperty(nameof(MachineInformation.MachineLogs))]
        public virtual MachineInformation Machine { get; set; }
    }
}