// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HonjiMES.CncModels
{
    public partial class MachineProcessTime
    {

        /// <summary>
        /// 唯一碼
        /// </summary>
        [Column("id", TypeName = "int(5)")]
        public int Id { get; set; }

        /// <summary>
        /// &#21807;&#19968;&#30908;
        /// </summary>
        [Column("machineid", TypeName = "int(5)")]
        public int Machineid { get; set; }

        /// <summary>
        /// &#27231;&#21488;&#21517;&#31281;
        /// </summary>
        [Required]
        [Column("machinename", TypeName = "varchar(12)")]
        public string Machinename { get; set; }

        /// <summary>
        /// &#27284;&#26696;&#21517;&#31281;
        /// </summary>
        [Required]
        [Column("filename", TypeName = "varchar(255)")]
        public string Filename { get; set; }

        /// <summary>
        /// &#31243;&#24335;&#35387;&#35299;
        /// </summary>
        [Column("comment", TypeName = "varchar(255)")]
        public string Comment { get; set; }

        [Column("procedure")]
        [StringLength(255)]
        public string Procedure { get; set; }
        /// <summary>
        /// &#38283;&#22987;&#26178;&#38291;
        /// </summary>
        [Column("start_time", TypeName = "timestamp")]
        public DateTime? StartTime { get; set; }

        /// <summary>
        /// &#32080;&#26463;&#26178;&#38291;
        /// </summary>
        [Column("end_time", TypeName = "timestamp")]
        public DateTime? EndTime { get; set; }
    }
}