// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.CncModels
{
    /// <summary>
    /// &#27231;&#21488;&#32676;&#32068;ID&#33287;&#27231;&#21488;ID&#32068;&#21512;
    /// </summary>
    [Table("machine_group__machine_information")]
    public partial class MachineGroupMachineInformation
    {
        /// <summary>
        /// 唯一碼
        /// </summary>
        [Key]
        [Column("id", TypeName = "int(5)")]
        public int Id { get; set; }
        /// <summary>
        /// &#27231;&#21488;ID
        /// </summary>
        [Column("machine_id", TypeName = "int(5)")]
        public int MachineId { get; set; }
        /// <summary>
        /// &#27231;&#21488;&#32676;&#32068;ID
        /// </summary>
        [Column("machine_group_id", TypeName = "int(5)")]
        public int MachineGroupId { get; set; }

        [ForeignKey(nameof(MachineId))]
        [InverseProperty(nameof(MachineInformation.MachineGroupMachineInformations))]
        public virtual MachineInformation Machine { get; set; }
        [ForeignKey(nameof(MachineGroupId))]
        [InverseProperty("MachineGroupMachineInformations")]
        public virtual MachineGroup MachineGroup { get; set; }
    }
}