// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.CncModels
{
    /// <summary>
    /// &#27231;&#21488;&#32676;&#32068;
    /// </summary>
    [Table("machine_groups")]
    public partial class MachineGroup
    {
        public MachineGroup()
        {
            MachineGroupMachineInformations = new HashSet<MachineGroupMachineInformation>();
        }

        /// <summary>
        /// 唯一碼
        /// </summary>
        [Key]
        [Column("id", TypeName = "int(5)")]
        public int Id { get; set; }
        /// <summary>
        /// &#27231;&#21488;&#32676;&#32068;&#21517;
        /// </summary>
        [Required]
        [Column("name", TypeName = "varchar(255)")]
        public string Name { get; set; }
        /// <summary>
        /// &#32239;&#24230;
        /// </summary>
        [Column("latitude")]
        public float? Latitude { get; set; }
        /// <summary>
        /// &#32147;&#24230;
        /// </summary>
        [Column("longitude")]
        public float? Longitude { get; set; }

        [InverseProperty(nameof(MachineGroupMachineInformation.MachineGroup))]
        public virtual ICollection<MachineGroupMachineInformation> MachineGroupMachineInformations { get; set; }
    }
}