// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.CncModels
{
    [Table("maintain_info")]
    public partial class MaintainInfo
    {
        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        /// <summary>
        /// &#20445;&#39178;&#21517;&#31281;
        /// </summary>
        [Required]
        [Column("maintain_name", TypeName = "varchar(200)")]
        public string MaintainName { get; set; }
        /// <summary>
        /// &#20998;&#39006;
        /// </summary>
        [Required]
        [Column("type", TypeName = "varchar(50)")]
        public string Type { get; set; }
        /// <summary>
        /// &#21034;&#38500;&#27161;&#31034;
        /// </summary>
        [Column("delete_flag", TypeName = "int(11)")]
        public int DeleteFlag { get; set; }
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
    }
}