// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.CncModels
{
    [Table("maintain")]
    public partial class Maintain
    {
        /// <summary>
        /// 唯一碼
        /// </summary>
        [Key]
        [Column("id", TypeName = "int(5)")]
        public int Id { get; set; }
        /// <summary>
        /// &#27231;&#21488;&#21517;&#31281;
        /// </summary>
        [Column("machine_id", TypeName = "int(5)")]
        public int MachineId { get; set; }
        /// <summary>
        /// &#20445;&#39178;&#38917;&#30446;
        /// </summary>
        [Column("maintain_item", TypeName = "int(11)")]
        public int MaintainItem { get; set; }
        /// <summary>
        /// &#20445;&#39178;&#26178;&#38291;
        /// </summary>
        [Column("maintain_time", TypeName = "datetime")]
        public DateTime MaintainTime { get; set; }
        /// <summary>
        /// &#36913;&#26399;
        /// </summary>
        [Column("cycle", TypeName = "int(5)")]
        public int? Cycle { get; set; }
        /// <summary>
        /// E-mail 1
        /// </summary>
        [Column("email_1", TypeName = "varchar(100)")]
        public string Email1 { get; set; }
        /// <summary>
        /// E-mail 2
        /// </summary>
        [Column("email_2", TypeName = "varchar(100)")]
        public string Email2 { get; set; }
        /// <summary>
        /// E-mail 3
        /// </summary>
        [Column("email_3", TypeName = "varchar(100)")]
        public string Email3 { get; set; }
        /// <summary>
        /// &#29376;&#24907;
        /// </summary>
        [Column("status", TypeName = "int(1)")]
        public int Status { get; set; }
        [Column("notice", TypeName = "int(1)")]
        public int? Notice { get; set; }
        /// <summary>
        /// &#20445;&#39178;&#32467;&#26463;&#26178;&#38291;
        /// </summary>
        [Column("maintain_finish_time", TypeName = "datetime")]
        public DateTime? MaintainFinishTime { get; set; }
        /// <summary>
        /// &#26032;&#22686;&#26178;&#38291;
        /// </summary>
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        /// <summary>
        /// &#26356;&#26032;&#26178;&#38291;
        /// </summary>
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
    }
}