// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.CncModels
{
    /// <summary>
    /// &#21152;&#24037;&#31243;&#24335;&#32000;&#37636;
    /// </summary>
    [Table("nc_file_logs")]
    public partial class NcFileLog
    {
        /// <summary>
        /// 唯一碼
        /// </summary>
        [Key]
        [Column("id", TypeName = "int(5)")]
        public int Id { get; set; }
        /// <summary>
        /// &#27284;&#26696;ID
        /// </summary>
        [Column("file_id", TypeName = "int(5)")]
        public int FileId { get; set; }
        /// <summary>
        /// &#22519;&#34892;&#21205;&#20316;
        /// </summary>
        [Required]
        [Column("action", TypeName = "varchar(50)")]
        public string Action { get; set; }
        /// <summary>
        /// &#21040;&#30340;&#36335;&#24465;
        /// </summary>
        [Column("path", TypeName = "varchar(255)")]
        public string Path { get; set; }
        /// <summary>
        /// &#24478;&#21738;&#20491;&#22320;&#26041;
        /// </summary>
        [Column("from", TypeName = "int(5)")]
        public int From { get; set; }
        /// <summary>
        /// &#21040;&#21738;&#20491;&#22320;&#26041;
        /// </summary>
        [Column("to", TypeName = "int(5)")]
        public int To { get; set; }
        /// <summary>
        /// &#20351;&#29992;&#32773;ID
        /// </summary>
        [Column("user_id", TypeName = "int(5)")]
        public int UserId { get; set; }
        /// <summary>
        /// &#31243;&#24335;&#30906;&#35469;
        /// </summary>
        [Column("nc_check", TypeName = "int(3)")]
        public int? NcCheck { get; set; }
        /// <summary>
        /// &#35338;&#24687;
        /// </summary>
        [Column("message", TypeName = "varchar(255)")]
        public string Message { get; set; }
        /// <summary>
        /// &#26032;&#22686;&#26178;&#38291;
        /// </summary>
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
    }
}