// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.CncModels
{
    [Table("order")]
    public partial class Order
    {
        /// <summary>
        /// 唯一碼
        /// </summary>
        [Key]
        [Column("id", TypeName = "int(5)")]
        public int Id { get; set; }
        /// <summary>
        /// &#26989;&#21209;&#34399;
        /// </summary>
        [Required]
        [Column("business_id", TypeName = "varchar(10)")]
        public string BusinessId { get; set; }
        /// <summary>
        /// &#26009;&#34399;
        /// </summary>
        [Required]
        [Column("part_no", TypeName = "varchar(20)")]
        public string PartNo { get; set; }
        /// <summary>
        /// &#21517;&#31281;
        /// </summary>
        [Required]
        [Column("name", TypeName = "varchar(255)")]
        public string Name { get; set; }
        /// <summary>
        /// &#25976;&#37327;
        /// </summary>
        [Column("quantity", TypeName = "int(8)")]
        public int Quantity { get; set; }
        /// <summary>
        /// &#26448;&#36074;
        /// </summary>
        [Column("material", TypeName = "varchar(100)")]
        public string Material { get; set; }
        /// <summary>
        /// &#36914;&#26009;&#23610;&#23544;
        /// </summary>
        [Column("dimension", TypeName = "varchar(100)")]
        public string Dimension { get; set; }
        /// <summary>
        /// &#35330;&#21934;&#29376;&#24907;
        /// </summary>
        [Column("status", TypeName = "varchar(100)")]
        public string Status { get; set; }
        /// <summary>
        /// &#26159;&#21542;&#38283;&#24037;(1:YES)
        /// </summary>
        [Column("process_status", TypeName = "smallint(6)")]
        public short? ProcessStatus { get; set; }
        /// <summary>
        /// &#35330;&#21934;&#20132;&#26399;
        /// </summary>
        [Column("order_delivery_time", TypeName = "date")]
        public DateTime? OrderDeliveryTime { get; set; }
        /// <summary>
        /// &#26032;&#22686;&#26178;&#38291;
        /// </summary>
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        /// <summary>
        /// &#26356;&#26032;&#26178;&#38291;
        /// </summary>
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
    }
}