// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.CncModels
{
    [Table("process_rule")]
    public partial class ProcessRule
    {
        /// <summary>
        /// 唯一碼
        /// </summary>
        [Key]
        [Column("id", TypeName = "int(5)")]
        public int Id { get; set; }
        [Column("row", TypeName = "smallint(6)")]
        public short Row { get; set; }
        [Column("order_id", TypeName = "int(5)")]
        public int OrderId { get; set; }
        [Column("process_id", TypeName = "int(5)")]
        public int? ProcessId { get; set; }
        /// <summary>
        /// &#24615;&#36074; 1:&#24288;&#20839; 2:&#22996;&#22806; 
        /// </summary>
        [Column("property", TypeName = "int(11)")]
        public int? Property { get; set; }
        /// <summary>
        /// &#37096;&#38272;
        /// </summary>
        [Column("department", TypeName = "int(11)")]
        public int? Department { get; set; }
        /// <summary>
        /// &#35069;&#31243;&#21517;&#31281;
        /// </summary>
        [Required]
        [Column("process_name", TypeName = "varchar(30)")]
        public string ProcessName { get; set; }
        /// <summary>
        /// &#38928;&#35336;&#23436;&#24037;&#26085;
        /// </summary>
        [Column("finish_time", TypeName = "date")]
        public DateTime? FinishTime { get; set; }
        /// <summary>
        /// &#24037;&#26178;
        /// </summary>
        [Column("standard_time", TypeName = "varchar(10)")]
        public string StandardTime { get; set; }
        /// <summary>
        /// &#21934;&#20729;
        /// </summary>
        [Column("price")]
        public float Price { get; set; }
        /// <summary>
        /// &#37329;&#38989;
        /// </summary>
        [Column("price_all")]
        public float PriceAll { get; set; }
        /// <summary>
        /// &#23526;&#38555;&#23436;&#24037;&#26085;
        /// </summary>
        [Column("actual_finish_time", TypeName = "date")]
        public DateTime? ActualFinishTime { get; set; }
        /// <summary>
        /// &#26032;&#22686;&#26178;&#38291;
        /// </summary>
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
    }
}