// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.CncModels
{
    [Table("purchase_info")]
    public partial class PurchaseInfo
    {
        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        /// <summary>
        /// &#25505;&#36092;&#21934;id
        /// </summary>
        [Column("purchase_id", TypeName = "int(11)")]
        public int PurchaseId { get; set; }
        /// <summary>
        /// &#35215;&#26684;&#21517;&#31281;
        /// </summary>
        [Required]
        [Column("name", TypeName = "varchar(100)")]
        public string Name { get; set; }
        /// <summary>
        /// &#21934;&#20301;
        /// </summary>
        [Required]
        [Column("unit", TypeName = "varchar(50)")]
        public string Unit { get; set; }
        /// <summary>
        /// &#21934;&#20729;
        /// </summary>
        [Column("price")]
        public float Price { get; set; }
        /// <summary>
        /// &#25976;&#37327;
        /// </summary>
        [Column("count", TypeName = "int(11)")]
        public int Count { get; set; }
        /// <summary>
        /// &#37329;&#38989;
        /// </summary>
        [Column("price_all")]
        public float PriceAll { get; set; }
        /// <summary>
        /// &#20633;&#35387;
        /// </summary>
        [Column("remark", TypeName = "varchar(255)")]
        public string Remark { get; set; }
        [Column("create_user", TypeName = "int(11)")]
        public int CreateUser { get; set; }
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
    }
}