// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.CncModels
{
    [Table("purchase")]
    public partial class Purchase
    {
        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        /// <summary>
        /// &#25505;&#36092;&#21934;&#34399;
        /// </summary>
        [Required]
        [Column("purchase_no", TypeName = "varchar(100)")]
        public string PurchaseNo { get; set; }
        /// <summary>
        /// &#26989;&#21209;&#34399;
        /// </summary>
        [Required]
        [Column("business_id", TypeName = "varchar(100)")]
        public string BusinessId { get; set; }
        /// <summary>
        /// &#26009;&#34399;
        /// </summary>
        [Required]
        [Column("part_no", TypeName = "varchar(100)")]
        public string PartNo { get; set; }
        /// <summary>
        /// &#24288;&#21830;&#20195;&#34399;
        /// </summary>
        [Column("vendor_id", TypeName = "int(11)")]
        public int VendorId { get; set; }
        /// <summary>
        /// &#38651;&#35441;
        /// </summary>
        [Required]
        [Column("tel", TypeName = "varchar(100)")]
        public string Tel { get; set; }
        /// <summary>
        /// &#20659;&#30495;
        /// </summary>
        [Required]
        [Column("fax", TypeName = "varchar(100)")]
        public string Fax { get; set; }
        /// <summary>
        /// &#38928;&#20132;&#26085;&#26399;
        /// </summary>
        [Column("delivery_time", TypeName = "timestamp")]
        public DateTime DeliveryTime { get; set; }
        /// <summary>
        /// &#32317;&#35336;
        /// </summary>
        [Column("cost")]
        public float Cost { get; set; }
        /// <summary>
        /// &#20633;&#35387;
        /// </summary>
        [Column("remark", TypeName = "varchar(255)")]
        public string Remark { get; set; }
        /// <summary>
        /// &#29376;&#24907;
        /// </summary>
        [Column("status", TypeName = "tinyint(4)")]
        public sbyte Status { get; set; }
        /// <summary>
        /// &#24314;&#31435;&#20154;&#21729;
        /// </summary>
        [Column("create_user", TypeName = "int(11)")]
        public int CreateUser { get; set; }
        /// <summary>
        /// &#26356;&#26032;&#20154;&#21729;
        /// </summary>
        [Column("update_user", TypeName = "int(11)")]
        public int UpdateUser { get; set; }
        /// <summary>
        /// &#24314;&#31435;&#26178;&#38291;
        /// </summary>
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        /// <summary>
        /// &#26356;&#26032;&#20154;&#21729;
        /// </summary>
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
    }
}