// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.CncModels
{
    /// <summary>
    /// &#20351;&#29992;&#32773;&#32000;&#37636;
    /// </summary>
    [Table("user_logs")]
    public partial class UserLog
    {
        /// <summary>
        /// 唯一碼
        /// </summary>
        [Key]
        [Column("id", TypeName = "int(5)")]
        public int Id { get; set; }
        /// <summary>
        /// &#20351;&#29992;&#32773;ID
        /// </summary>
        [Column("user_id", TypeName = "int(5)")]
        public int UserId { get; set; }
        /// <summary>
        /// &#30331;&#20837;&#26178;&#38291;
        /// </summary>
        [Column("login_time", TypeName = "timestamp")]
        public DateTime LoginTime { get; set; }
        /// <summary>
        /// &#30331;&#20986;&#26178;&#38291;
        /// </summary>
        [Column("logout_time", TypeName = "timestamp")]
        public DateTime? LogoutTime { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("UserLogs")]
        public virtual User User { get; set; }
    }
}