// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.CncModels
{
    /// <summary>
    /// &#20351;&#29992;&#32773;
    /// </summary>
    [Table("users")]
    public partial class User
    {
        public User()
        {
            MachineInformations = new HashSet<MachineInformation>();
            UserLogs = new HashSet<UserLog>();
        }

        /// <summary>
        /// 唯一碼
        /// </summary>
        [Key]
        [Column("id", TypeName = "int(5)")]
        public int Id { get; set; }
        /// <summary>
        /// &#20351;&#29992;&#32773;&#21517;&#31281;
        /// </summary>
        [Required]
        [Column("username", TypeName = "varchar(50)")]
        public string Username { get; set; }
        /// <summary>
        /// &#30495;&#23526;&#22995;&#21517;
        /// </summary>
        [Required]
        [Column("realname", TypeName = "varchar(50)")]
        public string Realname { get; set; }
        /// <summary>
        /// &#23494;&#30908;
        /// </summary>
        [Required]
        [Column("password", TypeName = "tinytext")]
        public string Password { get; set; }
        /// <summary>
        /// &#27402;&#38480;
        /// </summary>
        [Column("permission", TypeName = "int(11)")]
        public int Permission { get; set; }
        /// <summary>
        /// &#25480;&#27402;&#34892;&#28858;
        /// </summary>
        [Column("auth_action", TypeName = "text")]
        public string AuthAction { get; set; }
        /// <summary>
        /// &#21855;&#29992;&#29376;&#24907;0:&#20572;&#29992;1:&#21855;&#29992; 
        /// </summary>
        [Column("status", TypeName = "int(1)")]
        public int Status { get; set; }
        /// <summary>
        /// &#26032;&#22686;&#26178;&#38291;
        /// </summary>
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        /// <summary>
        /// &#37096;&#38272;
        /// </summary>
        [Column("department", TypeName = "int(11)")]
        public int Department { get; set; }

        [InverseProperty(nameof(MachineInformation.User))]
        public virtual ICollection<MachineInformation> MachineInformations { get; set; }
        [InverseProperty(nameof(UserLog.User))]
        public virtual ICollection<UserLog> UserLogs { get; set; }
    }
}