// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.CncModels
{
    [Table("vendor")]
    public partial class Vendor
    {
        /// <summary>
        /// 唯一碼
        /// </summary>
        [Key]
        [Column("id", TypeName = "int(5)")]
        public int Id { get; set; }
        /// <summary>
        /// &#24288;&#21830;&#20195;&#34399;
        /// </summary>
        [Required]
        [Column("vendor_no", TypeName = "varchar(20)")]
        public string VendorNo { get; set; }
        /// <summary>
        /// &#24288;&#21830;&#21517;&#31281;
        /// </summary>
        [Required]
        [Column("vendor_name", TypeName = "varchar(255)")]
        public string VendorName { get; set; }
        /// <summary>
        /// &#24288;&#21830;&#20316;&#26989;&#20839;&#23481;
        /// </summary>
        [Column("vendor_data", TypeName = "varchar(255)")]
        public string VendorData { get; set; }
        /// <summary>
        /// &#36899;&#32097;&#38651;&#35441;
        /// </summary>
        [Column("tel", TypeName = "varchar(255)")]
        public string Tel { get; set; }
        /// <summary>
        /// &#20659;&#30495;&#34399;&#30908;
        /// </summary>
        [Column("fax", TypeName = "varchar(255)")]
        public string Fax { get; set; }
        /// <summary>
        /// &#20449;&#31665;
        /// </summary>
        [Column("mail", TypeName = "varchar(255)")]
        public string Mail { get; set; }
        /// <summary>
        /// &#32879;&#32097;&#20154;
        /// </summary>
        [Required]
        [Column("contact_name", TypeName = "varchar(255)")]
        public string ContactName { get; set; }
        /// <summary>
        /// &#20633;&#35387;
        /// </summary>
        [Column("remark", TypeName = "varchar(255)")]
        public string Remark { get; set; }
        /// <summary>
        /// &#35731;&#20351;&#29992;&#32773;&#19981;&#20877;&#30475;&#21040; 
        /// </summary>
        [Column("visible", TypeName = "tinyint(4)")]
        public sbyte Visible { get; set; }
        /// <summary>
        /// &#26032;&#22686;&#26178;&#38291;
        /// </summary>
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        /// <summary>
        /// &#26356;&#26032;&#26178;&#38291;
        /// </summary>
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
    }
}