// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.Models
{
[Table("adjust_head")]
    public partial class AdjustHead
    {
        public AdjustHead()
        {
            AdjustDetails = new HashSet<AdjustDetail>();
        }

        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        [Required]
        [Column("adjust_no", TypeName = "varchar(50)")]
        public string AdjustNo { get; set; }
        [Column("link_order", TypeName = "varchar(50)")]
        public string LinkOrder { get; set; }
        [Column("temp", TypeName = "int(11)")]
        public int? Temp { get; set; }
        [Column("status", TypeName = "int(11)")]
        public int? Status { get; set; }
        [Column("remarks", TypeName = "varchar(50)")]
        public string Remarks { get; set; }
        [Column("delete_flag", TypeName = "int(11)")]
        public int DeleteFlag { get; set; }
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        [Column("create_user", TypeName = "int(11)")]
        public int CreateUser { get; set; }
        [Column("update_time", TypeName = "timestamp")]
        public DateTime? UpdateTime { get; set; }
        [Column("update_user", TypeName = "int(11)")]
        public int? UpdateUser { get; set; }

        [InverseProperty(nameof(AdjustDetail.AdjustHead))]
        public virtual ICollection<AdjustDetail> AdjustDetails { get; set; }
    }
}