// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.Models
{
[Table("billof_purchase_head")]
    public partial class BillofPurchaseHead
    {
        public BillofPurchaseHead()
        {
            BillofPurchaseDetails = new HashSet<BillofPurchaseDetail>();
        }

        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        [Required]
        [Column("billof_purchase_no", TypeName = "varchar(100)")]
        public string BillofPurchaseNo { get; set; }
        [Column("type", TypeName = "int(11)")]
        public int? Type { get; set; }
        [Column("status", TypeName = "int(11)")]
        public int Status { get; set; }
        [Column("remarks", TypeName = "varchar(100)")]
        public string Remarks { get; set; }
        [Column("billof_purchase_date", TypeName = "timestamp")]
        public DateTime? BillofPurchaseDate { get; set; }
        [Column("check_time", TypeName = "timestamp")]
        public DateTime? CheckTime { get; set; }
        [Column("price_all", TypeName = "int(11)")]
        public int PriceAll { get; set; }
        [Column("delete_flag", TypeName = "tinyint(4)")]
        public sbyte DeleteFlag { get; set; }
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        [Column("create_user", TypeName = "int(11)")]
        public int CreateUser { get; set; }
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
        [Column("update_user", TypeName = "int(11)")]
        public int? UpdateUser { get; set; }

        [InverseProperty("BillofPurchase")]
        public virtual ICollection<BillofPurchaseDetail> BillofPurchaseDetails { get; set; }
    }
}