// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.Models
{
[Table("billof_purchase_return")]
    public partial class BillofPurchaseReturn
    {
        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        [Column("return_no", TypeName = "varchar(50)")]
        public string ReturnNo { get; set; }
        [Column("billof_purchase_detail_id", TypeName = "int(11)")]
        public int BillofPurchaseDetailId { get; set; }
        [Column("warehouse_id", TypeName = "int(11)")]
        public int WarehouseId { get; set; }
        [Column("quantity")]
        public float Quantity { get; set; }
        [Column("price")]
        public float? Price { get; set; }
        [Column("price_all")]
        public float PriceAll { get; set; }
        [Column("unit", TypeName = "varchar(50)")]
        public string Unit { get; set; }
        [Column("unit_count")]
        public float? UnitCount { get; set; }
        [Column("unit_price")]
        public float? UnitPrice { get; set; }
        [Required]
        [Column("reason", TypeName = "varchar(100)")]
        public string Reason { get; set; }
        [Column("remarks", TypeName = "varchar(100)")]
        public string Remarks { get; set; }
        [Column("delete_flag", TypeName = "tinyint(4)")]
        public sbyte DeleteFlag { get; set; }
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        [Column("create_user", TypeName = "int(11)")]
        public int CreateUser { get; set; }
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
        [Column("update_user", TypeName = "int(11)")]
        public int? UpdateUser { get; set; }

        [ForeignKey(nameof(BillofPurchaseDetailId))]
        [InverseProperty("BillofPurchaseReturns")]
        public virtual BillofPurchaseDetail BillofPurchaseDetail { get; set; }
        [ForeignKey(nameof(WarehouseId))]
        [InverseProperty("BillofPurchaseReturns")]
        public virtual Warehouse Warehouse { get; set; }
    }
}