// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.Models
{
[Table("material_requisition_detail")]
    public partial class MaterialRequisitionDetail
    {
        public MaterialRequisitionDetail()
        {
            MaterialReceives = new HashSet<MaterialReceive>();
        }

        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        [Column("material_requisition_id", TypeName = "int(11)")]
        public int MaterialRequisitionId { get; set; }
        [Column("material_basic_id", TypeName = "int(11)")]
        public int MaterialBasicId { get; set; }
        [Required]
        [Column("material_no", TypeName = "varchar(50)")]
        public string MaterialNo { get; set; }
        [Required]
        [Column("name", TypeName = "varchar(50)")]
        public string Name { get; set; }
        [Column("quantity", TypeName = "int(11)")]
        public int Quantity { get; set; }
        [Column("remarks", TypeName = "varchar(100)")]
        public string Remarks { get; set; }
        [Column("delete_flag", TypeName = "tinyint(4)")]
        public sbyte DeleteFlag { get; set; }
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        [Column("create_user", TypeName = "int(11)")]
        public int CreateUser { get; set; }
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
        [Column("update_user", TypeName = "int(11)")]
        public int? UpdateUser { get; set; }

        [ForeignKey("MaterialBasicId")]
        [InverseProperty("MaterialRequisitionDetails")]
        public virtual MaterialBasic MaterialBasic { get; set; }
        [ForeignKey("MaterialRequisitionId")]
        [InverseProperty("MaterialRequisitionDetails")]
        public virtual MaterialRequisition MaterialRequisition { get; set; }
        [InverseProperty("MaterialRequisitionDetail")]
        public virtual ICollection<MaterialReceive> MaterialReceives { get; set; }
    }
}