// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.Models
{
[Table("material_receive")]
    public partial class MaterialReceive
    {
        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        [Column("quantity", TypeName = "int(11)")]
        public int Quantity { get; set; }
        [Column("remarks", TypeName = "varchar(100)")]
        public string Remarks { get; set; }
        [Column("delete_flag", TypeName = "tinyint(4)")]
        public sbyte DeleteFlag { get; set; }
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        [Column("create_user", TypeName = "int(11)")]
        public int CreateUser { get; set; }
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
        [Column("update_user", TypeName = "int(11)")]
        public int? UpdateUser { get; set; }
        [Column("material_requisition_detail_id", TypeName = "int(11)")]
        public int MaterialRequisitionDetailId { get; set; }
        [Column("material_id", TypeName = "int(11)")]
        public int MaterialId { get; set; }

        [ForeignKey("MaterialId")]
        [InverseProperty("MaterialReceives")]
        public virtual Material Material { get; set; }
        [ForeignKey("MaterialRequisitionDetailId")]
        [InverseProperty("MaterialReceives")]
        public virtual MaterialRequisitionDetail MaterialRequisitionDetail { get; set; }
    }
}