// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.Models
{
[Table("m_bill_of_material")]
    public partial class MBillOfMaterial
    {
        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        [Column("pid", TypeName = "int(11)")]
        public int? Pid { get; set; }
        [Column("name", TypeName = "varchar(45)")]
        public string Name { get; set; }
        [Column("product_basic_id", TypeName = "int(11)")]
        public int? ProductBasicId { get; set; }
        [Column("bom_id", TypeName = "int(11)")]
        public int? BomId { get; set; }
        [Column("serial_number", TypeName = "int(11)")]
        public int SerialNumber { get; set; }
        [Column("process_id", TypeName = "int(11)")]
        public int ProcessId { get; set; }
        [Required]
        [Column("process_no", TypeName = "varchar(50)")]
        public string ProcessNo { get; set; }
        [Required]
        [Column("process_name", TypeName = "varchar(100)")]
        public string ProcessName { get; set; }
        [Column("process_lead_time", TypeName = "decimal(10,2)")]
        public decimal ProcessLeadTime { get; set; }
        [Column("process_time", TypeName = "decimal(10,2)")]
        public decimal ProcessTime { get; set; }
        [Column("process_cost", TypeName = "decimal(10,2)")]
        public decimal ProcessCost { get; set; }
        [Column("draw_no", TypeName = "varchar(50)")]
        public string DrawNo { get; set; }
        [Column("manpower", TypeName = "int(11)")]
        public int? Manpower { get; set; }
        [Column("producing_machine", TypeName = "varchar(50)")]
        public string ProducingMachine { get; set; }
        [Column("status", TypeName = "int(11)")]
        public int Status { get; set; }
        [Required]
        [Column("type", TypeName = "varchar(50)")]
        public string Type { get; set; }
        [Column("remarks", TypeName = "varchar(100)")]
        public string Remarks { get; set; }
        [Column("version", TypeName = "decimal(10,2)")]
        public decimal Version { get; set; }
        [Column("delete_flag", TypeName = "int(11)")]
        public int DeleteFlag { get; set; }
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        [Column("create_user", TypeName = "int(11)")]
        public int CreateUser { get; set; }
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
        [Column("update_user", TypeName = "int(11)")]
        public int UpdateUser { get; set; }

        [ForeignKey(nameof(ProcessId))]
        [InverseProperty("MBillOfMaterials")]
        public virtual Process Process { get; set; }
    }
}