// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.Models
{
[Table("order_detail")]
    public partial class OrderDetail
    {
        public OrderDetail()
        {
            SaleDetailNews = new HashSet<SaleDetailNew>();
        }

        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        [Column("order_id", TypeName = "int(11)")]
        public int OrderId { get; set; }
        [Required]
        [Column("customer_no", TypeName = "varchar(50)")]
        public string CustomerNo { get; set; }
        [Column("serial", TypeName = "int(11)")]
        public int Serial { get; set; }
        [Column("product_basic_id", TypeName = "int(11)")]
        public int ProductBasicId { get; set; }
        [Column("product_id", TypeName = "int(11)")]
        public int? ProductId { get; set; }
        [Column("quantity", TypeName = "int(11)")]
        public int Quantity { get; set; }
        [Column("originPrice", TypeName = "int(11)")]
        public int OriginPrice { get; set; }
        [Column("discount", TypeName = "int(11)")]
        public int? Discount { get; set; }
        [Column("discount_price", TypeName = "int(11)")]
        public int? DiscountPrice { get; set; }
        [Column("price", TypeName = "int(11)")]
        public int Price { get; set; }
        [Column("delivered", TypeName = "int(11)")]
        public int? Delivered { get; set; }
        [Required]
        [Column("unit", TypeName = "varchar(50)")]
        public string Unit { get; set; }
        [Column("due_date", TypeName = "timestamp")]
        public DateTime DueDate { get; set; }
        [Column("remark", TypeName = "varchar(50)")]
        public string Remark { get; set; }
        [Column("reply_date", TypeName = "timestamp")]
        public DateTime ReplyDate { get; set; }
        [Column("replyRemark", TypeName = "varchar(50)")]
        public string ReplyRemark { get; set; }
        [Required]
        [Column("machine_no", TypeName = "varchar(100)")]
        public string MachineNo { get; set; }
        [Column("drawing", TypeName = "varchar(50)")]
        public string Drawing { get; set; }
        [Column("ink", TypeName = "varchar(50)")]
        public string Ink { get; set; }
        [Column("label", TypeName = "varchar(50)")]
        public string Label { get; set; }
        [Column("package", TypeName = "int(11)")]
        public int? Package { get; set; }
        [Column("reply", TypeName = "int(11)")]
        public int? Reply { get; set; }
        [Column("sale_count", TypeName = "int(11)")]
        public int SaleCount { get; set; }
        [Column("delete_flag", TypeName = "int(11)")]
        public int DeleteFlag { get; set; }
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        [Column("create_user", TypeName = "int(11)")]
        public int CreateUser { get; set; }
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
        [Column("update_user", TypeName = "int(11)")]
        public int? UpdateUser { get; set; }

        [ForeignKey(nameof(OrderId))]
        [InverseProperty(nameof(OrderHead.OrderDetails))]
        public virtual OrderHead Order { get; set; }
        [ForeignKey(nameof(ProductId))]
        [InverseProperty("OrderDetails")]
        public virtual Product Product { get; set; }
        [ForeignKey(nameof(ProductBasicId))]
        [InverseProperty("OrderDetails")]
        public virtual ProductBasic ProductBasic { get; set; }
        [InverseProperty(nameof(SaleDetailNew.OrderDetail))]
        public virtual ICollection<SaleDetailNew> SaleDetailNews { get; set; }
    }
}