// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.Models
{
[Table("order_head")]
    public partial class OrderHead
    {
        public OrderHead()
        {
            OrderDetails = new HashSet<OrderDetail>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("order_no", TypeName = "varchar(50)")]
        public string OrderNo { get; set; }
        [Required]
        [Column("customer_no", TypeName = "varchar(50)")]
        public string CustomerNo { get; set; }
        [Column("order_date", TypeName = "timestamp")]
        public DateTime OrderDate { get; set; }
        [Column("start_date", TypeName = "timestamp")]
        public DateTime StartDate { get; set; }
        [Column("finish_date", TypeName = "timestamp")]
        public DateTime FinishDate { get; set; }
        [Column("customer")]
        public int Customer { get; set; }
        [Column("create_date", TypeName = "timestamp")]
        public DateTime CreateDate { get; set; }
        [Column("create_user")]
        public int CreateUser { get; set; }

        [InverseProperty("Order")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}