// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.Models
{
[Table("order_head")]
    public partial class OrderHead
    {
        public OrderHead()
        {
            OrderDetails = new HashSet<OrderDetail>();
            SaleDetailNews = new HashSet<SaleDetailNew>();
        }

        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        [Required]
        [Column("order_no", TypeName = "varchar(50)")]
        public string OrderNo { get; set; }
        [Column("order_type", TypeName = "varchar(50)")]
        public string OrderType { get; set; }
        [Required]
        [Column("customer_no", TypeName = "varchar(50)")]
        public string CustomerNo { get; set; }
        [Column("order_date", TypeName = "timestamp")]
        public DateTime OrderDate { get; set; }
        [Column("reply_date", TypeName = "timestamp")]
        public DateTime? ReplyDate { get; set; }
        [Column("start_date", TypeName = "timestamp")]
        public DateTime? StartDate { get; set; }
        [Column("finish_date", TypeName = "timestamp")]
        public DateTime? FinishDate { get; set; }
        [Column("customer", TypeName = "int(11)")]
        public int Customer { get; set; }
        [Column("status", TypeName = "tinyint(4)")]
        public sbyte Status { get; set; }
        [Column("remarks", TypeName = "varchar(100)")]
        public string Remarks { get; set; }
        [Column("delete_flag", TypeName = "int(11)")]
        public int DeleteFlag { get; set; }
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        [Column("create_user", TypeName = "int(11)")]
        public int CreateUser { get; set; }
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
        [Column("update_user", TypeName = "int(11)")]
        public int? UpdateUser { get; set; }

        [InverseProperty("Order")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [InverseProperty("Order")]
        public virtual ICollection<SaleDetailNew> SaleDetailNews { get; set; }
    }
}