// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.Models
{
[Table("permission")]
    public partial class Permission
    {
        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        [Column("new", TypeName = "int(11)")]
        public int New { get; set; }
        [Column("edit", TypeName = "int(11)")]
        public int Edit { get; set; }
        [Column("del", TypeName = "int(11)")]
        public int Del { get; set; }
        [Column("search", TypeName = "int(11)")]
        public int Search { get; set; }
        [Column("sort", TypeName = "int(11)")]
        public int Sort { get; set; }
        [Column("import", TypeName = "int(11)")]
        public int Import { get; set; }
        [Column("export", TypeName = "int(11)")]
        public int Export { get; set; }
        [Column("copy_add", TypeName = "int(11)")]
        public int CopyAdd { get; set; }
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        [Column("create_user", TypeName = "int(11)")]
        public int CreateUser { get; set; }
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
        [Column("update_user", TypeName = "int(11)")]
        public int? UpdateUser { get; set; }
    }
}