// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.Models
{
[Table("product_sn")]
    public partial class ProductSn
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("product_number", TypeName = "varchar(100)")]
        public string ProductNumber { get; set; }
        [Column("product_id")]
        public int? ProductId { get; set; }
        [Column("customer_id")]
        public int? CustomerId { get; set; }
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        [Column("create_user")]
        public int CreateUser { get; set; }
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
        [Column("update_user")]
        public int? UpdateUser { get; set; }
    }
}