// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.Models
{
[Table("product_log")]
    public partial class ProductLog
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("product_id")]
        public int ProductId { get; set; }
        [Column("original")]
        public int Original { get; set; }
        [Column("quantity")]
        public int Quantity { get; set; }
        [Column("message", TypeName = "varchar(50)")]
        public string Message { get; set; }
        [Column("create_date", TypeName = "timestamp")]
        public DateTime CreateDate { get; set; }
        [Column("create_user")]
        public int CreateUser { get; set; }

        [ForeignKey("ProductId")]
        [InverseProperty("ProductLogs")]
        public virtual Product Product { get; set; }
    }
}