// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.Models
{
[Table("purchase_detail")]
    public partial class PurchaseDetail
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("purchase_id")]
        public int PurchaseId { get; set; }
        [Column("purchase_type")]
        public int PurchaseType { get; set; }
        [Column("supplier_id")]
        public int SupplierId { get; set; }
        [Column("order_id")]
        public int? OrderId { get; set; }
        [Column("data_id")]
        public int DataId { get; set; }
        [Required]
        [Column("data_no", TypeName = "varchar(50)")]
        public string DataNo { get; set; }
        [Required]
        [Column("data_name", TypeName = "varchar(50)")]
        public string DataName { get; set; }
        [Column("specification", TypeName = "varchar(50)")]
        public string Specification { get; set; }
        [Column("quantity")]
        public int Quantity { get; set; }
        [Column("originPrice")]
        public int OriginPrice { get; set; }
        [Column("price")]
        public int Price { get; set; }
        [Column("remarks", TypeName = "varchar(50)")]
        public string Remarks { get; set; }
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        [Column("create_user")]
        public int CreateUser { get; set; }

        [ForeignKey("PurchaseId")]
        [InverseProperty("PurchaseDetails")]
        public virtual PurchaseHead Purchase { get; set; }
    }
}