// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.Models
{
[Table("requisition_detail")]
    public partial class RequisitionDetail
    {
        public RequisitionDetail()
        {
            Receives = new HashSet<Receive>();
        }

        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        [Column("requisition_id", TypeName = "int(11)")]
        public int RequisitionId { get; set; }
        [Column(TypeName = "int(11)")]
        public int? Lv { get; set; }
        [Column("name", TypeName = "varchar(50)")]
        public string Name { get; set; }
        [Column("material_basic_id", TypeName = "int(11)")]
        public int? MaterialBasicId { get; set; }
        [Column("material_name", TypeName = "varchar(50)")]
        public string MaterialName { get; set; }
        [Column("material_no", TypeName = "varchar(50)")]
        public string MaterialNo { get; set; }
        [Column("material_specification", TypeName = "varchar(50)")]
        public string MaterialSpecification { get; set; }
        [Column("product_basic_id", TypeName = "int(11)")]
        public int? ProductBasicId { get; set; }
        [Column("product_no", TypeName = "varchar(50)")]
        public string ProductNo { get; set; }
        [Column("product_number", TypeName = "varchar(50)")]
        public string ProductNumber { get; set; }
        [Column("product_name", TypeName = "varchar(50)")]
        public string ProductName { get; set; }
        [Column("product_specification", TypeName = "varchar(50)")]
        public string ProductSpecification { get; set; }
        [Column("quantity", TypeName = "int(11)")]
        public int Quantity { get; set; }
        [Column("remarks", TypeName = "varchar(100)")]
        public string Remarks { get; set; }
        [Column("delete_flag", TypeName = "tinyint(4)")]
        public sbyte DeleteFlag { get; set; }
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        [Column("create_user", TypeName = "int(11)")]
        public int CreateUser { get; set; }
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
        [Column("update_user", TypeName = "int(11)")]
        public int? UpdateUser { get; set; }
        [Column("ismaterial")]
        public bool? Ismaterial { get; set; }

        [ForeignKey(nameof(MaterialBasicId))]
        [InverseProperty("RequisitionDetails")]
        public virtual MaterialBasic MaterialBasic { get; set; }
        [ForeignKey(nameof(ProductBasicId))]
        [InverseProperty("RequisitionDetails")]
        public virtual ProductBasic ProductBasic { get; set; }
        [ForeignKey(nameof(RequisitionId))]
        [InverseProperty("RequisitionDetails")]
        public virtual Requisition Requisition { get; set; }
        [InverseProperty(nameof(Receive.RequisitionDetail))]
        public virtual ICollection<Receive> Receives { get; set; }
    }
}