// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.Models
{
[Table("return_sale")]
    public partial class ReturnSale
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("warehouse_id")]
        public int WarehouseId { get; set; }
        [Column("quantity")]
        public int Quantity { get; set; }
        [Column("reason", TypeName = "varchar(50)")]
        public string Reason { get; set; }
        [Column("remarks", TypeName = "varchar(500)")]
        public string Remarks { get; set; }
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        [Column("create_user")]
        public int CreateUser { get; set; }
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
        [Column("update_user")]
        public int? UpdateUser { get; set; }
        [Column("sale_detail_new_id")]
        public int SaleDetailNewId { get; set; }

        [ForeignKey("SaleDetailNewId")]
        [InverseProperty("ReturnSales")]
        public virtual SaleDetailNew SaleDetailNew { get; set; }
        [ForeignKey("WarehouseId")]
        [InverseProperty("ReturnSales")]
        public virtual Warehouse Warehouse { get; set; }
    }
}