// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.Models
{
[Table("saleold")]
    public partial class Saleold
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("sale_no", TypeName = "varchar(50)")]
        public string SaleNo { get; set; }
        [Column("project_no")]
        public int ProjectNo { get; set; }
        [Column("product_no")]
        public int ProductNo { get; set; }
        [Required]
        [Column("name", TypeName = "varchar(50)")]
        public string Name { get; set; }
        [Column("quantity")]
        public int Quantity { get; set; }
        [Column("price")]
        public int Price { get; set; }
        [Required]
        [Column("specification", TypeName = "varchar(50)")]
        public string Specification { get; set; }
        [Column("sale_date", TypeName = "date")]
        public DateTime SaleDate { get; set; }
        [Required]
        [Column("customer", TypeName = "varchar(50)")]
        public string Customer { get; set; }
        [Required]
        [Column("customer_no", TypeName = "varchar(50)")]
        public string CustomerNo { get; set; }
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        [Column("create_user")]
        public int CreateUser { get; set; }
        [Required]
        [Column("status", TypeName = "varchar(50)")]
        public string Status { get; set; }
        [Column("remarks", TypeName = "varchar(50)")]
        public string Remarks { get; set; }
        [Column("update_user")]
        public int? UpdateUser { get; set; }
    }
}