// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.Models
{
[Table("sale_detail_new")]
    public partial class SaleDetailNew
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("sale_id")]
        public int SaleId { get; set; }
        [Column("order_id")]
        public int OrderId { get; set; }
        [Column("order_detail_id")]
        public int OrderDetailId { get; set; }
        [Column("product_id")]
        public int ProductId { get; set; }
        [Required]
        [Column("product_no", TypeName = "varchar(50)")]
        public string ProductNo { get; set; }
        [Column("status")]
        public int Status { get; set; }
        [Required]
        [Column("name", TypeName = "varchar(50)")]
        public string Name { get; set; }
        [Column("specification", TypeName = "varchar(50)")]
        public string Specification { get; set; }
        [Column("quantity")]
        public int Quantity { get; set; }
        [Column("originPrice")]
        public int OriginPrice { get; set; }
        [Column("price")]
        public int Price { get; set; }
        [Column("remarks", TypeName = "varchar(50)")]
        public string Remarks { get; set; }
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        [Column("create_user")]
        public int CreateUser { get; set; }
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
        [Column("update_user")]
        public int? UpdateUser { get; set; }
        [Column("delete_flag")]
        public sbyte DeleteFlag { get; set; }

        [ForeignKey("OrderId")]
        [InverseProperty("SaleDetailNews")]
        public virtual OrderHead Order { get; set; }
        [ForeignKey("OrderDetailId")]
        [InverseProperty("SaleDetailNews")]
        public virtual OrderDetail OrderDetail { get; set; }
        [ForeignKey("ProductId")]
        [InverseProperty("SaleDetailNews")]
        public virtual Product Product { get; set; }
        [ForeignKey("SaleId")]
        [InverseProperty("SaleDetailNews")]
        public virtual SaleHead Sale { get; set; }
    }
}