// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.Models
{
[Table("sale_log")]
    public partial class SaleLog
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("sale_id")]
        public int SaleId { get; set; }
        [Column("type")]
        public int Type { get; set; }
        [Column("message", TypeName = "varchar(200)")]
        public string Message { get; set; }
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        [Column("create_user")]
        public int CreateUser { get; set; }
        [Column("update_user")]
        public int? UpdateUser { get; set; }
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
    }
}