// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.Models
{
[Table("sale_detail_new")]
    public partial class SaleDetailNew
    {
        public SaleDetailNew()
        {
            ReturnSales = new HashSet<ReturnSale>();
        }

        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        [Column("sale_id", TypeName = "int(11)")]
        public int SaleId { get; set; }
        [Column("order_id", TypeName = "int(11)")]
        public int OrderId { get; set; }
        [Column("order_detail_id", TypeName = "int(11)")]
        public int OrderDetailId { get; set; }
        [Column("product_basic_id", TypeName = "int(11)")]
        public int ProductBasicId { get; set; }
        [Column("product_id", TypeName = "int(11)")]
        public int? ProductId { get; set; }
        [Required]
        [Column("product_no", TypeName = "varchar(50)")]
        public string ProductNo { get; set; }
        [Column("status", TypeName = "int(11)")]
        public int Status { get; set; }
        [Required]
        [Column("name", TypeName = "varchar(50)")]
        public string Name { get; set; }
        [Column("specification", TypeName = "varchar(50)")]
        public string Specification { get; set; }
        [Column("quantity", TypeName = "int(11)")]
        public int Quantity { get; set; }
        [Column("originPrice", TypeName = "int(11)")]
        public int OriginPrice { get; set; }
        [Column("price", TypeName = "int(11)")]
        public int Price { get; set; }
        [Column("remarks", TypeName = "varchar(50)")]
        public string Remarks { get; set; }
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        [Column("create_user", TypeName = "int(11)")]
        public int CreateUser { get; set; }
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
        [Column("update_user", TypeName = "int(11)")]
        public int? UpdateUser { get; set; }
        [Column("delete_flag", TypeName = "tinyint(4)")]
        public sbyte DeleteFlag { get; set; }

        [ForeignKey(nameof(OrderId))]
        [InverseProperty(nameof(OrderHead.SaleDetailNews))]
        public virtual OrderHead Order { get; set; }
        [ForeignKey(nameof(OrderDetailId))]
        [InverseProperty("SaleDetailNews")]
        public virtual OrderDetail OrderDetail { get; set; }
        [ForeignKey(nameof(ProductId))]
        [InverseProperty("SaleDetailNews")]
        public virtual Product Product { get; set; }
        [ForeignKey(nameof(ProductBasicId))]
        [InverseProperty("SaleDetailNews")]
        public virtual ProductBasic ProductBasic { get; set; }
        [ForeignKey(nameof(SaleId))]
        [InverseProperty(nameof(SaleHead.SaleDetailNews))]
        public virtual SaleHead Sale { get; set; }
        [InverseProperty(nameof(ReturnSale.SaleDetailNew))]
        public virtual ICollection<ReturnSale> ReturnSales { get; set; }
    }
}