// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.Models
{
[Table("sale_head")]
    public partial class SaleHead
    {
        public SaleHead()
        {
            SaleDetailNews = new HashSet<SaleDetailNew>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("sale_no", TypeName = "varchar(100)")]
        public string SaleNo { get; set; }
        [Column("temp")]
        public int? Temp { get; set; }
        [Column("status")]
        public int Status { get; set; }
        [Column("remarks", TypeName = "varchar(100)")]
        public string Remarks { get; set; }
        [Column("sale_date", TypeName = "timestamp")]
        public DateTime? SaleDate { get; set; }
        [Column("price_all")]
        public int PriceAll { get; set; }
        [Column("delete_flag")]
        public sbyte DeleteFlag { get; set; }
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        [Column("create_user")]
        public int CreateUser { get; set; }
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
        [Column("update_user")]
        public int? UpdateUser { get; set; }

        [InverseProperty("Sale")]
        public virtual ICollection<SaleDetailNew> SaleDetailNews { get; set; }
    }
}