// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.Models
{
[Table("supplier")]
    public partial class Supplier
    {
        public Supplier()
        {
            BillofPurchaseDetails = new HashSet<BillofPurchaseDetail>();
        }

        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        [Required]
        [Column("name", TypeName = "varchar(50)")]
        public string Name { get; set; }
        [Required]
        [Column("code", TypeName = "varchar(50)")]
        public string Code { get; set; }
        [Column("contact_name", TypeName = "varchar(100)")]
        public string ContactName { get; set; }
        [Required]
        [Column("phone", TypeName = "varchar(50)")]
        public string Phone { get; set; }
        [Required]
        [Column("fax", TypeName = "varchar(50)")]
        public string Fax { get; set; }
        [Required]
        [Column("email", TypeName = "varchar(50)")]
        public string Email { get; set; }
        [Required]
        [Column("address", TypeName = "varchar(50)")]
        public string Address { get; set; }
        [Required]
        [Column("bank", TypeName = "varchar(50)")]
        public string Bank { get; set; }
        [Required]
        [Column("branch", TypeName = "varchar(50)")]
        public string Branch { get; set; }
        [Required]
        [Column("uniform_no", TypeName = "varchar(50)")]
        public string UniformNo { get; set; }
        [Required]
        [Column("account", TypeName = "varchar(50)")]
        public string Account { get; set; }
        [Column("remarks", TypeName = "varchar(50)")]
        public string Remarks { get; set; }
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        [Column("create_user", TypeName = "int(11)")]
        public int CreateUser { get; set; }
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
        [Column("update_user", TypeName = "int(11)")]
        public int? UpdateUser { get; set; }
        [Column("delete_flag", TypeName = "tinyint(4)")]
        public sbyte DeleteFlag { get; set; }

        [InverseProperty("Supplier")]
        public virtual ICollection<BillofPurchaseDetail> BillofPurchaseDetails { get; set; }
    }
}