// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.Models
{
[Table("users")]
    public partial class User
    {
        public User()
        {
            UserRoles = new HashSet<UserRole>();
        }

        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        [Required]
        [Column("username", TypeName = "varchar(50)")]
        public string Username { get; set; }
        [Required]
        [Column("realname", TypeName = "varchar(50)")]
        public string Realname { get; set; }
        [Required]
        [Column("password", TypeName = "tinytext")]
        public string Password { get; set; }
        [Column("permission", TypeName = "int(11)")]
        public int Permission { get; set; }
        [Column("department", TypeName = "int(11)")]
        public int Department { get; set; }
        [Column("remarks", TypeName = "varchar(50)")]
        public string Remarks { get; set; }
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        [Column("create_user", TypeName = "int(11)")]
        public int CreateUser { get; set; }
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
        [Column("update_user", TypeName = "int(11)")]
        public int? UpdateUser { get; set; }
        [Column("delete_flag", TypeName = "tinyint(4)")]
        public sbyte DeleteFlag { get; set; }

        [InverseProperty(nameof(UserRole.Users))]
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}