// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.Models
{
[Table("user_roles")]
    public partial class UserRole
    {
        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        [Column("roles", TypeName = "varchar(10)")]
        public string Roles { get; set; }
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        [Column("create_user", TypeName = "int(11)")]
        public int CreateUser { get; set; }
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
        [Column("update_user", TypeName = "int(11)")]
        public int? UpdateUser { get; set; }
        [Column("delete_flag", TypeName = "tinyint(4)")]
        public sbyte DeleteFlag { get; set; }
        [Column("menu_id", TypeName = "int(11)")]
        public int MenuId { get; set; }
        [Column("users_id", TypeName = "int(11)")]
        public int UsersId { get; set; }
        [Column("memo", TypeName = "text")]
        public string Memo { get; set; }

        [ForeignKey(nameof(MenuId))]
        [InverseProperty("UserRoles")]
        public virtual Menu Menu { get; set; }
        [ForeignKey(nameof(UsersId))]
        [InverseProperty(nameof(User.UserRoles))]
        public virtual User Users { get; set; }
    }
}