// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.Models
{
[Table("wiproduct")]
    public partial class Wiproduct
    {
        public Wiproduct()
        {
            WiproductLogs = new HashSet<WiproductLog>();
        }

        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        [Column("wiproduct_basic_id", TypeName = "int(11)")]
        public int WiproductBasicId { get; set; }
        [Required]
        [Column("wiproduct_no", TypeName = "varchar(50)")]
        public string WiproductNo { get; set; }
        [Required]
        [Column("wiproduct_number", TypeName = "varchar(50)")]
        public string WiproductNumber { get; set; }
        [Required]
        [Column("name", TypeName = "varchar(50)")]
        public string Name { get; set; }
        [Column("quantity", TypeName = "int(11)")]
        public int Quantity { get; set; }
        [Column("quantity_limit", TypeName = "int(11)")]
        public int? QuantityLimit { get; set; }
        [Column("quantity_adv", TypeName = "int(11)")]
        public int QuantityAdv { get; set; }
        [Column("specification", TypeName = "varchar(50)")]
        public string Specification { get; set; }
        [Required]
        [Column("property", TypeName = "varchar(50)")]
        public string Property { get; set; }
        [Column("price", TypeName = "decimal(10,2)")]
        public decimal Price { get; set; }
        [Column("material_id", TypeName = "int(11)")]
        public int? MaterialId { get; set; }
        [Column("material_require", TypeName = "int(11)")]
        public int? MaterialRequire { get; set; }
        [Column("sub_inventory", TypeName = "varchar(50)")]
        public string SubInventory { get; set; }
        [Column("delete_flag", TypeName = "tinyint(4)")]
        public sbyte DeleteFlag { get; set; }
        [Column("remarks", TypeName = "varchar(50)")]
        public string Remarks { get; set; }
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        [Column("create_user", TypeName = "int(11)")]
        public int CreateUser { get; set; }
        [Column("update_time", TypeName = "timestamp")]
        public DateTime UpdateTime { get; set; }
        [Column("update_user", TypeName = "int(11)")]
        public int? UpdateUser { get; set; }
        [Column("warehouse_id", TypeName = "int(11)")]
        public int WarehouseId { get; set; }

        [ForeignKey(nameof(WarehouseId))]
        [InverseProperty("Wiproducts")]
        public virtual Warehouse Warehouse { get; set; }
        [ForeignKey(nameof(WiproductBasicId))]
        [InverseProperty("Wiproducts")]
        public virtual WiproductBasic WiproductBasic { get; set; }
        [InverseProperty(nameof(WiproductLog.Wiproduct))]
        public virtual ICollection<WiproductLog> WiproductLogs { get; set; }
    }
}