// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HonjiMES.Models
{
[Table("work_order_report_log")]
    public partial class WorkOrderReportLog
    {
        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        [Column("work_order_detail_id", TypeName = "int(11)")]
        public int WorkOrderDetailId { get; set; }
        [Column("report_type", TypeName = "int(11)")]
        public int ReportType { get; set; }
        [Column("purchase_id", TypeName = "int(11)")]
        public int? PurchaseId { get; set; }
        [Column("purchase_no", TypeName = "varchar(50)")]
        public string PurchaseNo { get; set; }
        [Column("draw_no", TypeName = "varchar(50)")]
        public string DrawNo { get; set; }
        [Column("manpower", TypeName = "int(11)")]
        public int? Manpower { get; set; }
        [Column("producing_machine_id", TypeName = "int(11)")]
        public int? ProducingMachineId { get; set; }
        [Column("producing_machine", TypeName = "varchar(50)")]
        public string ProducingMachine { get; set; }
        [Column("re_count", TypeName = "int(11)")]
        public int? ReCount { get; set; }
        [Column("remarks", TypeName = "varchar(50)")]
        public string Remarks { get; set; }
        [Column("status_o", TypeName = "int(11)")]
        public int StatusO { get; set; }
        [Column("status_n", TypeName = "int(11)")]
        public int StatusN { get; set; }
        [Column("due_start_time", TypeName = "timestamp")]
        public DateTime? DueStartTime { get; set; }
        [Column("due_end_time", TypeName = "timestamp")]
        public DateTime? DueEndTime { get; set; }
        [Column("actual_start_time", TypeName = "timestamp")]
        public DateTime? ActualStartTime { get; set; }
        [Column("actual_end_time", TypeName = "timestamp")]
        public DateTime? ActualEndTime { get; set; }
        [Column("delete_flag", TypeName = "int(11)")]
        public int DeleteFlag { get; set; }
        [Column("create_time", TypeName = "timestamp")]
        public DateTime CreateTime { get; set; }
        [Column("create_user", TypeName = "int(11)")]
        public int CreateUser { get; set; }

        [ForeignKey(nameof(PurchaseId))]
        [InverseProperty(nameof(PurchaseHead.WorkOrderReportLogs))]
        public virtual PurchaseHead Purchase { get; set; }
        [ForeignKey(nameof(WorkOrderDetailId))]
        [InverseProperty("WorkOrderReportLogs")]
        public virtual WorkOrderDetail WorkOrderDetail { get; set; }
    }
}